import Head from 'next/head'
import Image from 'next/image'
import Link, { LinkProps } from 'next/link'
// import Router from 'next/router'
import styles from '../styles/Home.module.css'
import styled, { css } from 'styled-components'
// import { useRouter } from 'next/router'

const H1 = styled.h1`
color: red;
`;

const Badge = styled.span`
  padding: 8px 16px;
  font-weight: bold;
  text-align: center;
  color: white;
  background: red;
  border-radius: 16px;
`;

type ButtonProps = {
  color: string;
  backgroundColor: string;
}
const Button = styled.button<ButtonProps>`
  color: ${(props) => props.color};
  background: ${(props) => props.backgroundColor};
  border: 2px solid ${(props) => props.color};

  font-size: 2em;
  margin: 1em;
  padding: 0.25em 1em;
  border-radius: 8px;
  cursor: pointer;
`;

// INFO: 赤ボーダー用スタイル
const redBox = css`
  padding: 0.25em 1em;
  border: 3px solid #f00;
  border-radius: 10px;
`;

// INFO: 青文字用スタイル
const font = css`
  color: #1e90ff;
  font-size: 2em;
`;

// INFO: 赤ボーダーと青文字を組み合わせ背景透過のボタン
const CustomButton = styled.button`
  background: transparent;
  margin: 1em;
  cursor: pointer;

  ${redBox};
  ${font};
`;

// INFO: 青文字スタイルを継承し、ボールドで表示するコンポーネント
const TextBold = styled.p`
  font-weight: bold;

  ${font};
`;

const TextBlueBold = styled.p`
  color: blue;
  font-weight: bold;
`;

const ExtendedBorderedText = styled(TextBlueBold)`
  padding: 8px 16px;
  border: 3px solid blue;
  border-radius: 8px;
`;

type BaseLinkProps = React.PropsWithChildren<LinkProps> & {
  className?: string;
  children: React.ReactNode;
}

const BaseLink = (props: BaseLinkProps) => {
  const { className, children, ...rest } = props;

  return (
    <Link {...rest}>
      <span className={className}>{children}</span>
    </Link>
  );
};

const StyledLink = styled(BaseLink)`
  color: #1e90ff;
  font-size: 2em;
`;

const TextA = styled.span`
  color: ${(props) => props.theme.colors.red};
  font-size: ${(props) => props.theme.fontSizes[4]};
  margin: ${(props) => props.theme.space[2]};
`;

export default function Home() {
  // const router = useRouter();
  // const onSubmit = () => {
  //   router.push('/ssr');

  //   // router.push({
  //   //   pathname: '/ssg',
  //   //   query: { keyword: 'hello' },
  //   // });
  // };

  // router.reload();
  // router.back();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <H1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </H1>
        <Badge>Hello!!!</Badge>
        <Button
          color="#f00"
          backgroundColor="transparent"
        >Hey, </Button>
        <Button
          color="white"
          backgroundColor="#1e90ff"
        >You!</Button>
        <CustomButton>Hahahahaaa!!!</CustomButton>
        <TextBold>Funny</TextBold>
        <TextBlueBold>青ボールドテキスト</TextBlueBold>
        <ExtendedBorderedText>継承されたボーダーテキスト</ExtendedBorderedText>
        <ExtendedBorderedText as="a" href="/">Go to Index</ExtendedBorderedText>
        <StyledLink href="/">Go to Index</StyledLink>
        <TextA>Themeから参照したスタイルを使用</TextA>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <Link href="/ssr">Go To SSR</Link>

        <Link href={{
          pathname: '/ssg',
          query: { keyword: 'hello' },
        }}>
          Go To SSG
        </Link>

        <Link href="/ssg">
          <button>Jump to SSG</button>
        </Link>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
